{% set name = "h5pickle" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfad571010e8018aaa5f7909a58fef2afe61e685bba8b3bca63fdcde494507b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - h5py
    - cachetools

test:
  imports:
    - h5pickle

about:
  home: https://pypi.org/project/h5pickle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper for h5py with pickle capabilities

  description: |
    This module provides a wrapper for the h5py classes to allow pickling of
    h5py objects. Basically the arguments to the h5py.File call are saved, and
    a new file is opened when a Group, Dataset or File is unpickled. Ergo, this
    will only work well on shared filesystems, and for reading files (SWMR
    should be fine too).
  dev_url: https://github.com/DaanVanVugt/h5pickle

extra:
  recipe-maintainers:
    - Anthchirp
